language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
install:
  - npm i -g cnpm
  - cnpm i -g lerna
  - lerna bootstrap
script:
  - npm run cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
